name: CI

on: [push]

jobs:
  build-llvm:
    if: "contains(github.event.head_commit.message, '[build]')"

    # timeout-minutes: 5  # Probably no timeout will suffice, but will see.
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            *.sh
          sparse-checkout-cone-mode: false

      - name: Check out llvm-project
        uses: actions/checkout@v3
        with:
          repository: llvm/llvm-project

      - name: Install mold the fast linker
        uses: rui314/setup-mold@v1

      - name: Install ninja build tool
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Build llvm
        run: |
          chmod +x build.sh
          bash build.sh

      - name: Run the tests
        run: |
          chmod +x test.sh
          bash test.sh

      - name: Zip the build
        run: |
          chmod +x zip.sh
          bash zip.sh

      - name: Upload as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: llvm
          path: zipped
          if-no-files-found: error
          retention-days: 1
